CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS divisions (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  image VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS spots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  division_id VARCHAR(50) NOT NULL,
  spot_name VARCHAR(190) NOT NULL,
  cost VARCHAR(50) DEFAULT NULL,
  hotel VARCHAR(190) DEFAULT NULL,
  map_url TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_spots_division FOREIGN KEY (division_id) REFERENCES divisions(id) ON DELETE CASCADE
);
